import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import LiquidEther from '@/components/LiquidEther';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} antialiased`}
      >
        <div className="fixed inset-0 -z-10">
        <LiquidEther
          colors={['#FFD1CA', '#E8B4AB', '#4A3845']}
          mouseForce={20}
          cursorSize={100}
          autoDemo={true}
          autoSpeed={0.3}
          autoIntensity={1.5}
          style={{ width: '100%', height: '100%' }}
        />
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
